# Site settings
title: Bobby Owolabi | The Intersection of Audio, Coding & Music
description: The Blog of Bobby Owolabi, Software Engineer, where he shares about his exploration of audio programming, software engineering and music.
url: "https://www.bobbyowolabi.com"
author:
  name: "Bobby Owolabi"
  email: "bobby@bobbyowolabi.com"
  url: "https://www.bobbyowolabi.com"
encoding: UTF-8

# Contact Links
social:
  github: "https://github.com/rowolabi"
  twitter: "https://twitter.com/bobbyowolabi"

# Build settings
baseurl: /  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
