name: Build and deploy Jekyll site to GitHub Pages

on:
  schedule:
    - cron: "50 13 * * *"
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          target_branch: 'gh-pages'
      - name: Configure Custom Domain
        env:
          CNAME: www.bobbyowolabi.com
        run: |
          echo $CNAME > CNAME
